version: "3.9"

services:
  web:
    container_name: django
    build: .
    command: >
      gunicorn social_book.wsgi:application --bind 0.0.0.0:9010 --workers=4
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    ports:
      - "9010:9010"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
    expose:
      - "9010"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testdbuser
      - POSTGRES_PASSWORD=test123

  
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "10080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/home/app/web/static/
      - ./media:/home/app/web/media/
    depends_on:
      - web


